### ISSUE TITLE
does this support scaling as a service?

### ISSUE THREAD

**Issue by cusspvz** [nixelsolutions/rancher-glusterfs-server#2]
I've seen [here](http://rancher.com/setting-up-a-scalable-and-highly-available-wordpress-environment-with-rancher-and-docker/) that you need to pass `GLUSTER_PEER` environment variable.

But thats not a good approach for scaling on-the-fly. Back to my question: Are you using dns discovery to discover other gluster nodes on the same service?

If not, can I implement it?

**Comment by cusspvz** [comment]
Well, seems [it has](https://github.com/nixelsolutions/rancher-glusterfs-server/blob/master/bin/run.sh#L19-L26)! Thank you! :)

**Comment by gustavocp** [comment]
could you explain how to do that? thank you

**Comment by nixelsolutions** [comment]
You don't need to do anything to scale up :) All containers will be automatically added to the cluster when they start for the first time.

The important thing is to declare SERVICE_NAME env. variable which value should be equal to the service name, by default it's gluster, so if you name this service "gluster" it'll work automatically by using DNS autodiscovery service from Rancher.

Note that this implementation was set over a very early Rancher version and because of that it might not work on newest versions. I sadly don't maintain this anymore.
